# Data Manipulation

#### 2.1.1 Getting Started

In [1]:
import torch

In [10]:
# same as arange() using numpy
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
x.numel()

12

In [14]:
x.shape

torch.Size([12])

In [25]:
# Note that if only one dimension known, it can be inferred by putting a -1 in place of a dimension. This is from the fomula w = n/h
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [28]:
# random samples from a normal dist ~N(0, 1).
torch.randn(3, 4)

tensor([[ 1.3098,  1.1563,  0.0201,  0.7509],
        [ 1.3807,  0.5160, -0.3739, -0.8764],
        [ 0.5893,  0.9636, -1.6998,  1.9303]])

In [29]:
# create a tensor from scratch
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

#### 2.1.2 Indexing and Slicing

Again, very similar ideas to python lists/NumPy arrays

In [43]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [45]:
# Easily modify elements
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[:2, :] = 12 # :2 gives usual slicing of anything beyond index 1 and : gives column indices in those rows
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

#### 2.1.3 Operations
Maths operations on tensors (think matrix operations)

In [54]:
# unary scaler operation on a tensor
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])